version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.2.8-apache-stretch-node-browsers
    steps:
      - checkout
      - run: echo "hello world"

  test:
    docker:
        - image: circleci/php:7.2.8-apache-stretch-node-browsers
    steps:
        - checkout 
        - run: echo "ayo"

workflows:
    version: 2
    build_and_test:
        jobs:
            - build
            - test:
                requires:
                    - build
